### PR TITLE
General update

### PR DESCRIPTION
**Pull request by therbom**
Framework overlay values are taken from 2.20.401.5 framework-res.apk.

Please note that this hasn't been tested yet. I'm also not sure about the value of config_deviceHardwareKeys.

### CODE REVIEW

**Comment by prototype-U** [comment]
The power_profile has incorrect frequencies for our phone. Where did you get that?

**Comment by therbom** [comment]
http://forum.xda-developers.com/showthread.php?t=2239511

I decompiled framework-res.apk from that ROM.

**Comment by prototype-U** [comment]
Inform the people in our DU thread about this commit. The compilers might test it

**Comment by therbom** [comment]
Done

**Pull request closed without merging**
